### model
model_name_or_path: /scratch/jc13140/hpml_project/data/Qwen/Qwen2.5-0.5B-Instruct
quantization_bit: 4  # choices: [8 (bnb/hqq/eetq), 4 (bnb/hqq), 3 (hqq), 2 (hqq)]
quantization_method: bnb  # choices: [bnb, hqq, eetq]
# resume_from_checkpoint: /scratch/jc13140/hpml_project/model/step2_model_qlora/checkpoint-6500

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
flash_attn: fa2

### dataset
dataset: step_2 # compress_task1_data_vp2
template: qwen
cutoff_len: 25000 
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16
#resume_from_checkpoint: true 

### output
output_dir: /scratch/jc13140/hpml_project/model/step2_model_qlora_redo/
logging_steps: 10
# save_steps: 500
save_strategy: "epoch"
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.03
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

### log
report_to: wandb
run_name: step_2_qlora_redo
